datasource: #增加数据库连接
    url: jdbc:mysql://127.0.0.1:3306/course?characterEncoding=utf-8&serverTimezone=UTC
    username: courseimooc
    password: courseimooc
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: /mapper/*.xml

logging:
  level:
    com:
      course:
        system:
          mapper: trace